Repository qdsfdhvh/compose-imageloader, pull requests merged in 2022-12, with the labels that each got.

#39 AppleMain source set can not find commonMain source set
  app/common/build.gradle.kts
Labels: bug

#40 Feature/custom logger
  app/android/src/main/java/com/seiko/imageloader/demo/DemoApp.kt
  app/android/src/main/java/com/seiko/imageloader/demo/MainActivity.kt
  app/common/build.gradle.kts
  app/common/src/commonMain/kotlin/com/seiko/imageloader/demo/ImageLoader.kt
  app/desktop/src/jvmMain/kotlin/com/seiko/imageloader/demo/Main.kt
  app/ios/src/uikitMain/kotlin/com.seiko.imageloader.demo/Main.kt
  app/macos/src/macosMain/kotlin/com/seiko/imageloader/demo/Main.kt
  app/web/src/jsMain/kotlin/Main.kt
  buildSrc/src/main/kotlin/Versions.kt
  image-loader/build.gradle.kts
  image-loader/src/androidMain/gif/com/seiko/imageloader/component/decoder/ImageDecoderDecoder.kt
  image-loader/src/androidMain/kotlin/com/seiko/imageloader/ImageLoaderBuilder.kt
  image-loader/src/androidMain/kotlin/com/seiko/imageloader/util/Bitmap.kt
  image-loader/src/androidMain/kotlin/com/seiko/imageloader/util/DebugLogger.kt
  image-loader/src/commonMain/compose/com/seiko/imageloader/AsyncImagePainter.kt
  image-loader/src/commonMain/kotlin/com/seiko/imageloader/ImageLoaderBuilder.kt
  image-loader/src/commonMain/kotlin/com/seiko/imageloader/component/keyer/KtorUrlKeyer.kt
  image-loader/src/commonMain/kotlin/com/seiko/imageloader/component/mapper/Base64Mapper.kt
  image-loader/src/commonMain/kotlin/com/seiko/imageloader/component/mapper/KtorUrlMapper.kt
  image-loader/src/commonMain/kotlin/com/seiko/imageloader/component/mapper/StringUriMapper.kt
  image-loader/src/commonMain/kotlin/com/seiko/imageloader/intercept/DiskCacheInterceptor.kt
  image-loader/src/commonMain/kotlin/com/seiko/imageloader/intercept/MemoryCacheInterceptor.kt
  image-loader/src/commonMain/kotlin/com/seiko/imageloader/util/Logger.kt
  image-loader/src/commonMain/kotlin/com/seiko/imageloader/util/Utils.kt
  image-loader/src/darwinMain/kotlin/com/seiko/imageloader/ImageLoaderBuilder.kt
  image-loader/src/darwinMain/kotlin/com/seiko/imageloader/util/DebugLogger.kt
  image-loader/src/desktopMain/kotlin/com/seiko/imageloader/ImageLoaderBuilder.kt
  image-loader/src/desktopMain/kotlin/com/seiko/imageloader/component/mapper/FileUriMapper.kt
  image-loader/src/desktopMain/kotlin/com/seiko/imageloader/util/DebugLogger.kt
  image-loader/src/jsMain/kotlin/com/seiko/imageloader/ImageLoaderBuilder.kt
  image-loader/src/jsMain/kotlin/com/seiko/imageloader/util/DebugLogger.kt
Labels: enhancement

#41 Chore/upgrade dependencies
  buildSrc/src/main/kotlin/Versions.kt
  image-loader-batik/build.gradle.kts
  image-loader/build.gradle.kts
Labels: dependencies

#42 Feature/retry if disk decode error
  app/common/src/commonMain/kotlin/com/seiko/imageloader/demo/ImageLoader.kt
  image-loader-batik/src/main/kotlin/com/seiko/imageloader/component/decoder/ImageIODecoder.kt
  image-loader/src/androidMain/gif/com/seiko/imageloader/component/decoder/ImageDecoderDecoder.kt
  image-loader/src/androidMain/kotlin/com/seiko/imageloader/component/decoder/BitmapFactoryDecoder.kt
  image-loader/src/commonMain/kotlin/com/seiko/imageloader/ImageLoader.kt
  image-loader/src/commonMain/kotlin/com/seiko/imageloader/component/decoder/DecodeResult.kt
  image-loader/src/commonMain/kotlin/com/seiko/imageloader/component/decoder/Decoder.kt
  image-loader/src/commonMain/kotlin/com/seiko/imageloader/intercept/DecodeInterceptor.kt
  image-loader/src/commonMain/kotlin/com/seiko/imageloader/intercept/DiskCacheInterceptor.kt
  image-loader/src/commonMain/kotlin/com/seiko/imageloader/intercept/EngineInterceptor.kt
  image-loader/src/commonMain/kotlin/com/seiko/imageloader/intercept/Interceptor.kt
  image-loader/src/commonMain/kotlin/com/seiko/imageloader/intercept/MappedInterceptor.kt
  image-loader/src/commonMain/kotlin/com/seiko/imageloader/intercept/MemoryCacheInterceptor.kt
  image-loader/src/commonMain/kotlin/com/seiko/imageloader/intercept/RealInterceptorChain.kt
  image-loader/src/commonMain/kotlin/com/seiko/imageloader/request/DataSource.kt
  image-loader/src/commonMain/kotlin/com/seiko/imageloader/request/ImageResult.kt
  image-loader/src/commonMain/kotlin/com/seiko/imageloader/request/Options.kt
  image-loader/src/skiaMain/kotlin/com/seiko/imageloader/component/decoder/GifDecoder.kt
  image-loader/src/skiaMain/kotlin/com/seiko/imageloader/component/decoder/SkiaImageDecoder.kt
  image-loader/src/skiaMain/kotlin/com/seiko/imageloader/component/decoder/SvgDecoder.kt
  kotlin-js-store/yarn.lock
Labels: enhancement

#43 Feature/refactor debug logger
  app/common/src/commonMain/kotlin/com/seiko/imageloader/demo/ImageLoader.kt
  image-loader/src/androidMain/kotlin/com/seiko/imageloader/util/PlatformLogger.kt
  image-loader/src/commonMain/kotlin/com/seiko/imageloader/util/DebugLogger.kt
  image-loader/src/commonMain/kotlin/com/seiko/imageloader/util/Logger.kt
  image-loader/src/darwinMain/kotlin/com/seiko/imageloader/util/PlatformLogger.kt
  image-loader/src/desktopMain/kotlin/com/seiko/imageloader/util/PlatformLogger.kt
  image-loader/src/jsMain/kotlin/com/seiko/imageloader/util/DebugLogger.kt
  image-loader/src/jsMain/kotlin/com/seiko/imageloader/util/PlatformLogger.kt
Labels: enhancement
