Repository qdsfdhvh/compose-imageloader, pull requests merged in 2023-05, with the labels that each got.

#140 update apple ioDispatcher
  image-loader/src/darwinMain/kotlin/com/seiko/imageloader/util/Platform.darwin.kt
  image-loader/src/jsMain/kotlin/com/seiko/imageloader/util/Platform.js.kt
  image-loader/src/jvmMain/kotlin/com/seiko/imageloader/util/Platform.jvm.kt
  image-loader/src/noJsMain/kotlin/com/seiko/imageloader/util/Platform.nojs.kt
Labels: ready_for_review

#144 remove default DebugLogger
  app/common/build.gradle.kts
  app/common/src/commonMain/kotlin/com/seiko/imageloader/demo/util/CustomKtorUrlFetcher.kt
  app/common/src/commonMain/kotlin/com/seiko/imageloader/demo/util/ImageLoader.kt
  gradle/libs.versions.toml
  image-loader/src/androidMain/kotlin/com/seiko/imageloader/util/PlatformLogger.kt
  image-loader/src/appleMain/kotlin/com/seiko/imageloader/util/PlatformLogger.kt
  image-loader/src/commonMain/kotlin/com/seiko/imageloader/util/DebugLogger.kt
  image-loader/src/commonMain/kotlin/com/seiko/imageloader/util/PlatformLogger.kt
  image-loader/src/desktopMain/kotlin/com/seiko/imageloader/util/PlatformLogger.kt
  image-loader/src/jsMain/kotlin/com/seiko/imageloader/util/PlatformLogger.kt
Labels: ready_for_review

#145 support gif repeat count
  app/common/src/commonMain/kotlin/com/seiko/imageloader/demo/scene/Common.kt
  image-loader/src/androidMain/kotlin/com/seiko/imageloader/component/decoder/GifDecoder.kt
  image-loader/src/androidMain/kotlin/com/seiko/imageloader/component/decoder/ImageDecoderDecoder.kt
  image-loader/src/androidMain/kotlin/com/seiko/imageloader/util/MovieDrawable.kt
  image-loader/src/androidMain/kotlin/com/seiko/imageloader/util/ScaleDrawable.kt
  image-loader/src/commonMain/kotlin/com/seiko/imageloader/option/Options.kt
  image-loader/src/skiaMain/kotlin/com/seiko/imageloader/component/decoder/GifDecoder.kt
  image-loader/src/skiaMain/kotlin/com/seiko/imageloader/util/GifPainter.kt
Labels: enhancement, ready_for_review

#150 try fix ios crash
  app/common/src/commonMain/kotlin/com/seiko/imageloader/demo/App.kt
  app/common/src/commonMain/kotlin/com/seiko/imageloader/demo/scene/Base64ImageScene.kt
  app/common/src/commonMain/kotlin/com/seiko/imageloader/demo/scene/BigImagesScene.kt
  app/common/src/commonMain/kotlin/com/seiko/imageloader/demo/scene/OtherImagesScene.kt
  image-loader/src/commonMain/kotlin/com/seiko/imageloader/cache/disk/DiskLruCache.kt
  image-loader/src/commonMain/kotlin/com/seiko/imageloader/cache/memory/WeakMemoryCache.kt
  image-loader/src/commonMain/kotlin/com/seiko/imageloader/component/fetcher/Base64Fetcher.kt
  image-loader/src/commonMain/kotlin/com/seiko/imageloader/util/Platform.kt
  image-loader/src/commonMain/singleton/com/seiko/imageloader/AsyncImagePainter.kt
  image-loader/src/darwinMain/kotlin/com/seiko/imageloader/util/Platform.darwin.kt
  image-loader/src/darwinMain/singleton/com/seiko/imageloader/component/SetupDefaultComponents.darwin.kt
  image-loader/src/desktopMain/singleton/com/seiko/imageloader/component/SetupDefaultComponents.desktop.kt
  image-loader/src/jvmMain/kotlin/com/seiko/imageloader/util/Platform.jvm.kt
  image-loader/src/skiaMain/kotlin/com/seiko/imageloader/component/SetupComponents.skia.kt
  image-loader/src/skiaMain/kotlin/com/seiko/imageloader/component/decoder/GifDecoder.kt
  image-loader/src/skiaMain/kotlin/com/seiko/imageloader/component/decoder/SkiaImageDecoder.kt
  image-loader/src/skiaMain/kotlin/com/seiko/imageloader/component/decoder/SvgDecoder.kt
  image-loader/src/skiaMain/kotlin/com/seiko/imageloader/util/GifPainter.kt
Labels: bug, ready_for_review

#156 remove okio default FileSystem in js
  app/web/build.gradle.kts
  app/web/src/jsMain/kotlin/Main.kt
  image-loader/build.gradle.kts
  image-loader/src/androidMain/kotlin/com/seiko/imageloader/cache/disk/DiskCacheBuilder.android.kt
  image-loader/src/androidMain/kotlin/com/seiko/imageloader/component/decoder/ImageDecoderDecoder.kt
  image-loader/src/appleMain/kotlin/com/seiko/imageloader/cache/disk/DiskCacheBuilder.apple.kt
  image-loader/src/appleMain/kotlin/com/seiko/imageloader/util/Platform.apple.kt
  image-loader/src/commonMain/kotlin/com/seiko/imageloader/cache/disk/DiskCacheBuilder.kt
  image-loader/src/commonMain/kotlin/com/seiko/imageloader/intercept/InterceptorsBuilder.kt
  image-loader/src/commonMain/kotlin/com/seiko/imageloader/util/Platform.kt
  image-loader/src/desktopMain/kotlin/com/seiko/imageloader/cache/disk/DiskCacheBuilder.desktop.kt
  image-loader/src/jsMain/kotlin/com/seiko/imageloader/cache/disk/DiskCacheBuilder.js.kt
  image-loader/src/jsMain/kotlin/com/seiko/imageloader/util/Platform.js.kt
  image-loader/src/jvmMain/kotlin/com/seiko/imageloader/util/Platform.jvm.kt
Labels: bug, ready_for_review

#159 fix gif also play when config turned off
  image-loader/src/androidMain/kotlin/com/seiko/imageloader/component/decoder/GifDecoder.kt
  image-loader/src/androidMain/kotlin/com/seiko/imageloader/component/decoder/ImageDecoderDecoder.kt
  image-loader/src/androidMain/kotlin/com/seiko/imageloader/util/MovieDrawable.kt
  image-loader/src/androidMain/kotlin/com/seiko/imageloader/util/ScaleDrawable.kt
  image-loader/src/skiaMain/kotlin/com/seiko/imageloader/component/decoder/GifDecoder.kt
  image-loader/src/skiaMain/kotlin/com/seiko/imageloader/util/GifPainter.kt
Labels: ready_for_review

#167 update github ci
  .github/workflows/assign-reviewers-bot.yml
  .github/workflows/label-approved-bot.yml
  .github/workflows/merge-bot.yml
  .github/workflows/publish.yml
  .github/workflows/release.yml
Labels: other

#166 Placeholder and Error painter
  image-loader/src/commonMain/kotlin/com/seiko/imageloader/model/ImageRequest.kt
  image-loader/src/commonMain/singleton/com/seiko/imageloader/AsyncImagePainter.kt
Labels: enhancement
